/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controler.LuuCSDL;
import Controler.LuuFIleController;
import Controler.MoFileController;
import Model.DBConnection;
import Model.User;
import java.io.IOException;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Admin
 */
public class NhapDiem extends javax.swing.JFrame {

    /**
     * Creates new form NhapDiem
     */
    public String maKT;
    public String magv;
    public String malop = "";

    public NhapDiem(String magv) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.magv = magv;

    }

    private NhapDiem() {

        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblDiem = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        btLuuF = new javax.swing.JButton();
        btMoF = new javax.swing.JButton();
        btBack = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btTim = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jtfAi = new javax.swing.JTextField();
        txtMalop = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jtfc1 = new javax.swing.JTextField();
        jtfc2 = new javax.swing.JTextField();
        jtfc3 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jtfscore = new javax.swing.JTextField();
        jbtsave = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(44, 62, 80));

        jScrollPane1.setBackground(new java.awt.Color(44, 62, 80));

        tblDiem.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "MSSV", "Câu 1", "Câu 2", "Câu 3", "Tổng điểm A"
            }
        ));
        tblDiem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDiemMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblDiem);

        jPanel1.setBackground(new java.awt.Color(44, 62, 80));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        btLuuF.setText("Lưu file");
        btLuuF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLuuFActionPerformed(evt);
            }
        });

        btMoF.setText("Mở file");
        btMoF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btMoFActionPerformed(evt);
            }
        });

        btBack.setText("< Trở về");
        btBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btBack, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btMoF, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btLuuF, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(btLuuF)
                .addGap(28, 28, 28)
                .addComponent(btMoF)
                .addGap(18, 18, 18)
                .addComponent(btBack)
                .addContainerGap(91, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(44, 62, 80));
        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 204));
        jLabel1.setText("Lớp: ");

        btTim.setText("Tìm");
        btTim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btTimActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(204, 204, 204));
        jLabel9.setText("Ai:");

        jtfAi.setText("1");
        jtfAi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtfAiMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtfAi)
                    .addComponent(txtMalop))
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addComponent(btTim, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtMalop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfAi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(18, 18, 18)
                .addComponent(btTim)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(44, 62, 80));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Điểm", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14), new java.awt.Color(204, 204, 204))); // NOI18N
        jPanel3.setName("Điểm"); // NOI18N

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 204, 204));
        jLabel4.setText("Câu 1 ");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 204, 204));
        jLabel5.setText("Câu 2 ");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 204, 204));
        jLabel6.setText("Câu 3 ");

        jtfc1.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                jtfc1InputMethodTextChanged(evt);
            }
        });
        jtfc1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfc1ActionPerformed(evt);
            }
        });

        jtfc3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfc3ActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(204, 204, 204));
        jLabel8.setText("Tổng Điểm A:");

        jbtsave.setText("Sửa điểm");
        jbtsave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtsaveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbtsave, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtfc1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(90, 90, 90)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtfc2, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 90, Short.MAX_VALUE)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtfc3, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(90, 90, 90)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtfscore, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(102, 102, 102))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5)
                        .addComponent(jLabel6)
                        .addComponent(jtfc2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jtfc3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel8)
                        .addComponent(jtfscore, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(jtfc1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(46, 46, 46)
                .addComponent(jbtsave)
                .addGap(45, 45, 45))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 263, Short.MAX_VALUE))
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBackActionPerformed

        // TODO add your handling code here:
//           FrameGiangVien dk = new FrameGiangVien();
        this.dispose();
//            dk.setVisible(true);

    }//GEN-LAST:event_btBackActionPerformed

    private void jtfAiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtfAiMouseClicked
        // TODO add your handling code here:
        jtfAi.setText("");
    }//GEN-LAST:event_jtfAiMouseClicked

    public Connection getConnection() {
        Connection con = null;

        try {
            con = DBConnection.getConnection();
        } catch (Exception ex) {
            System.out.println(ex.getMessage());
        }

        return con;
    }

    public ArrayList<User> ListUsers(String ValToSearch) {
        ArrayList<User> usersList = new ArrayList<User>();

        Statement st;
        ResultSet rs;

        try {
            Connection con = getConnection();
            st = con.createStatement();

            String searchQuery = "SELECT * FROM `bangdiema" + jtfAi.getText() + "` WHERE malop = '" + ValToSearch + "'";
            rs = st.executeQuery(searchQuery);

            User user;
            if (Integer.parseInt(jtfAi.getText()) == 4 || Integer.parseInt(jtfAi.getText()) == 2) {
                while (rs.next()) {

                    user = new User(
                            rs.getString("mssv"),
                            rs.getString("malop"),
                            rs.getFloat("diemcau1"),
                            rs.getFloat("diemcau2"),
                            rs.getFloat("diemcau3"),
                            rs.getFloat("tongdiema" + jtfAi.getText())
                    );
                    usersList.add(user);

                }
            } else {
                while (rs.next()) {

                    user = new User(
                            rs.getString("mssv"),
                            rs.getString("malop"),
                            rs.getFloat("tongdiema" + jtfAi.getText())
                    );
                    usersList.add(user);

                }
            }

        } catch (Exception ex) {
            System.out.println(ex.getMessage());
        }

        return usersList;
    }
    private void btTimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btTimActionPerformed

        // TODO add your handling code here:
        try {
            boolean check = false;

            Connection conn = DBConnection.getConnection();
            Statement stm = conn.createStatement();
            String sql1 = "select * from lophoc where magv='" + magv + "'";
            ResultSet rs1 = stm.executeQuery(sql1);
            while (rs1.next()) {
                if (rs1.getString("malophoc").equals(txtMalop.getText())) {
                    check = true;
                }
            }
            rs1.close();
            stm.close();
            conn.close();
            if (check == false) {
                JOptionPane.showMessageDialog(null, "Mã lớp đã chọn không hợp lệ", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
            } else {
                malop = txtMalop.getText();
                ArrayList<User> users;
                users = ListUsers(txtMalop.getText());
                DefaultTableModel model = new DefaultTableModel();
                if (Integer.parseInt(jtfAi.getText()) == 4 || Integer.parseInt(jtfAi.getText()) == 2) {
                    model.setColumnIdentifiers(new Object[]{"MSSV", "Mã lớp", "C1", "C2", "C3", "Tổng điểm A"});

                    Object[] row = new Object[6];

                    for (int i = 0; i < users.size(); i++) {
                        row[0] = users.get(i).getmssv();
                        row[1] = users.get(i).getmalop();
                        row[2] = users.get(i).getdiemcau1();
                        row[3] = users.get(i).getdiemcau2();
                        row[4] = users.get(i).getdiemcau3();
                        row[5] = users.get(i).gettongdiema4();
                        model.addRow(row);

                    }
                    tblDiem.setModel(model);
                } else {
                    model.setColumnIdentifiers(new Object[]{"MSSV", "Mã lớp", "Tổng điểm A"});

                    Object[] row = new Object[3];

                    for (int i = 0; i < users.size(); i++) {
                        row[0] = users.get(i).getmssv();
                        row[1] = users.get(i).getmalop();
                        row[2] = users.get(i).gettongdiema3();
                        model.addRow(row);

                    }
                    tblDiem.setModel(model);
                }
            }
        } catch (SQLException ex) {
            Logger.getLogger(NhapDiem.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_btTimActionPerformed
String mssv;
    private void tblDiemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDiemMouseClicked
        // TODO add your handling code here:
        int selectedRow = tblDiem.getSelectedRow();
        DefaultTableModel model = (DefaultTableModel) tblDiem.getModel();
        if (Integer.parseInt(jtfAi.getText()) == 4 || Integer.parseInt(jtfAi.getText()) == 2) {
            mssv=model.getValueAt(selectedRow, 0).toString();
            jtfc1.setText(model.getValueAt(selectedRow, 2).toString());
            jtfc2.setText(model.getValueAt(selectedRow, 3).toString());
            jtfc3.setText(model.getValueAt(selectedRow, 4).toString());
            jtfscore.setText(model.getValueAt(selectedRow, 5).toString());
        } else {
            mssv=model.getValueAt(selectedRow, 0).toString();
            jtfc1.setText("null");
            jtfc2.setText("null");
            jtfc3.setText("null");
            jtfscore.setText(model.getValueAt(selectedRow, 2).toString());
        }
    }//GEN-LAST:event_tblDiemMouseClicked

    private void jbtsaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtsaveActionPerformed
        // TODO add your handling code here:

        LuuCSDL controller = new LuuCSDL(jtfAi.getText(), jbtsave, tblDiem, malop, mssv, jtfc1, jtfc2, jtfc3,jtfscore);
        controller.setEvent();

    }//GEN-LAST:event_jbtsaveActionPerformed

    private void btLuuFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLuuFActionPerformed
        // TODO add your handling code here:
        if ("".equals(malop)) {
            JOptionPane.showMessageDialog(null, "Mã lớp đã chọn không hợp lệ", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
        } else {
            try {
                LuuFIleController controller = new LuuFIleController(malop, jtfAi.getText());
                controller.WriteExcel();
            } catch (IOException ex) {
                Logger.getLogger(NhapDiem.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btLuuFActionPerformed

    private void btMoFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btMoFActionPerformed
        // TODO add your handling code here:
        MoFileController controller = new MoFileController(jtfAi.getText(), tblDiem);
        try {
            controller.readExcel();
        } catch (IOException ex) {
            Logger.getLogger(NhapDiem.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btMoFActionPerformed

    private void jtfc1InputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_jtfc1InputMethodTextChanged
        // TODO add your handling code here:
       
    }//GEN-LAST:event_jtfc1InputMethodTextChanged

    private void jtfc1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfc1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfc1ActionPerformed

    private void jtfc3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfc3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfc3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NhapDiem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NhapDiem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NhapDiem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NhapDiem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NhapDiem().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btBack;
    private javax.swing.JButton btLuuF;
    private javax.swing.JButton btMoF;
    private javax.swing.JButton btTim;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbtsave;
    private javax.swing.JTextField jtfAi;
    private javax.swing.JTextField jtfc1;
    private javax.swing.JTextField jtfc2;
    private javax.swing.JTextField jtfc3;
    private javax.swing.JTextField jtfscore;
    private javax.swing.JTable tblDiem;
    private javax.swing.JTextField txtMalop;
    // End of variables declaration//GEN-END:variables
}
